Hepsi: Hatalar Includeler Derle Calistir

Hatalar:
	g++ -I ./include/ -o ./lib/Istisna.o -c ./src/Istisna.cpp

Includeler:

	g++ -I ./include/ -o ./lib/Dosya.o -c ./src/Dosya.cpp
	g++ -I ./include/ -o ./lib/Radiks.o -c ./src/Radiks.cpp
	g++ -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include/ -o ./lib/AVL.o -c ./src/AVL.cpp
	g++ -I ./include/ -o ./lib/Cozum.o -c ./src/Cozum.cpp
	

Derle:	
	g++ -I ./include/ -o ./bin/Test ./lib/Istisna.o ./lib/Dosya.o ./lib/Radiks.o ./lib/Dugum.o ./lib/AVL.o ./lib/Cozum.o ./src/Main.cpp

Calistir:
	./bin/Test
